import { useNavigate } from "react-router-dom";
import { IMAGES } from "../data";

function Icon({ name, className = "" }) {
  return <span className={`material-symbols-outlined ${className}`}>{name}</span>;
}

const VISCOSITY_GRADES = [
  {
    grade: "5W-30",
    desc: "Optimized for modern turbocharged gasoline direct injection (TGDI) engines. Provides superior cold-start protection and fuel economy.",
    badge: "Fuel Efficiency +3.2%",
    icon: "check_circle",
  },
  {
    grade: "10W-40",
    desc: "Engineered for high-mileage engines or extreme climate operations requiring a more robust oil film at operating temperatures.",
    badge: "Wear Protection Max",
    icon: "shield",
  },
];

const GLOBAL_STANDARDS = [
  {
    code: "API SP",
    desc: "Protects against Low Speed Pre-Ignition (LSPI) in downsized engines.",
  },
  {
    code: "ACEA C3",
    desc: "Mid-SAPS lubricant for diesel particulate filter (DPF) compatibility.",
  },
];

const OEM_APPROVALS = [
  {
    maker: "Mercedes-Benz",
    spec: "MB-Approval 229.51/229.52",
    icon: "precision_manufacturing",
  },
  {
    maker: "BMW",
    spec: "Longlife-04 / Longlife-12 FE",
    icon: "engineering",
  },
  {
    maker: "Volkswagen Group",
    spec: "VW 504 00 / 507 00",
    icon: "settings_suggest",
  },
  {
    maker: "Porsche",
    spec: "Porsche C30 / A40",
    icon: "verified",
  },
];

const LAB_ROWS = [
  {
    param: "Kinematic Viscosity @ 100°C",
    method: "ASTM D445",
    elite: "12.1 mm²/s",
    max: "14.5 mm²/s",
  },
  {
    param: "HTHS Viscosity @ 150°C",
    method: "ASTM D4683",
    elite: "3.5 mPa.s",
    max: "4.2 mPa.s",
  },
  {
    param: "Total Base Number (TBN)",
    method: "ASTM D2896",
    elite: "8.2 mg KOH/g",
    max: "10.5 mg KOH/g",
  },
  {
    param: "Flash Point",
    method: "ASTM D92",
    elite: "232 °C",
    max: "240 °C",
  },
  {
    param: "Pour Point",
    method: "ASTM D97",
    elite: "-42 °C",
    max: "-36 °C",
  },
];

const FRICTION_BENEFITS = [
  {
    icon: "eco",
    title: "Fuel Efficiency Advantage",
    desc: "Low-friction formulation reduces internal drag, leading to lower fuel consumption and reduced CO2 emissions.",
  },
  {
    icon: "timer",
    title: "Extended Drain Intervals",
    desc: "Outstanding oxidation stability allows for longer service periods without compromising engine protection.",
  },
  {
    icon: "speed",
    title: "Thermal Stability",
    desc: "Resists breakdown even under the extreme heat generated by modern high-performance turbochargers.",
  },
];

function Hero() {
  return (
    <section className="relative flex h-[728px] items-center overflow-hidden">
      <div className="absolute inset-0 z-0">
        <div className="absolute inset-0 z-10 bg-gradient-to-r from-[#1a1033]/55 via-[#2a0a14]/30 to-[#3a2a05]/25" />
        <div className="absolute inset-0 z-10 bg-gradient-to-r from-performance-red/20 via-transparent to-[#f7c948]/20" />
        <div className="absolute inset-x-0 top-0 z-10 h-24 bg-gradient-to-b from-black/70 to-transparent" />
        <div
          className="h-full w-full bg-cover bg-center"
          style={{ backgroundImage: `url('${IMAGES.image2}')` }}
        />
      </div>

      <div className="absolute inset-y-0 left-0 z-10 w-2/3 bg-gradient-to-r from-black/55 to-transparent md:w-1/2" />
      <div className="relative z-20 mx-auto w-full max-w-container-max px-margin-mobile text-safety-white md:px-margin-desktop">
        <span className="mb-4 inline-block rounded bg-industrial-green px-3 py-1 font-label-bold text-label-bold">
          Technical Advisory
        </span>
        <h1 className="mb-6 font-display-lg text-display-lg">
          Engineered Fluid Mastery
          <br />
          for Modern Propulsion
        </h1>
        <p className="mb-8 max-w-xl font-body-lg text-body-lg text-surface-variant">
          Detailed technical insights into viscosity management, API/ACEA
          compliance, and OEM certification for high-stress passenger vehicle
          engines.
        </p>
        <div className="flex flex-wrap gap-4">
          <button className="rounded bg-industrial-green px-8 py-4 font-label-bold text-label-bold text-safety-white transition-all hover:opacity-90">
            Download Spec Guide
          </button>
          <button className="rounded border border-safety-white px-8 py-4 font-label-bold text-label-bold text-safety-white transition-all hover:bg-safety-white hover:text-on-surface">
            OEM Approvals
          </button>
        </div>
      </div>
    </section>
  );
}

function ShopByNeed() {
  const navigate = useNavigate();
  const go = (filter) => navigate(`/products?filter=${encodeURIComponent(filter)}`);

  const NEEDS = [
    { label: "Shop by Need", desc: "Get to the right oil, coolant, or service fluid without hunting through the menu.", icon: "tune", cta: false },
    { label: "Shop by Vehicle Type", desc: "Cars, trucks, marine, equipment", icon: "directions_car", filter: "Vehicle Type" },
    { label: "Shop by Viscosity", desc: "Start with 5W-30 motor oil", icon: "oil_barrel", filter: "Viscosity" },
    { label: "Shop Motor Oil", desc: "Synthetic, blend, conventional", icon: "local_gas_station", filter: "Motor Oil" },
    { label: "Shop Gear Oil", desc: "GL-4, GL-5, synthetic gear lube", icon: "settings", filter: "Gear Oil" },
    { label: "Shop Coolant", desc: "Antifreeze by color and vehicle", icon: "ac_unit", filter: "Coolant" },
    { label: "Best Sellers & Deals", desc: "Top products and current offers", icon: "local_offer", filter: "Best Sellers" },
  ];

  return (
    <section className="bg-surface-subtle px-margin-mobile py-section-gap md:px-margin-desktop">
      <div className="mx-auto max-w-container-max">
        <div className="mb-10 text-center">
          <h2 className="mb-3 font-headline-lg text-headline-lg text-on-surface">
            Shop by Need
          </h2>
          <p className="mx-auto max-w-2xl font-body-md text-on-surface-variant">
            Get to the right oil, coolant, or service fluid without hunting through
            the menu.
          </p>
        </div>
        <div className="flex flex-wrap justify-center gap-4">
          {NEEDS.filter((n) => !n.cta).map((n) => (
            <button
              key={n.label}
              onClick={() => go(n.filter)}
              className="group flex w-full flex-col items-start gap-2 rounded-xl border border-outline-variant bg-safety-white p-5 text-left shadow-sm transition-all hover:-translate-y-1 hover:border-industrial-green hover:shadow-md sm:w-[calc(50%-0.5rem)] lg:w-[calc(33.333%-1.1rem)]"
            >
              <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary-container text-on-primary-container">
                <Icon name={n.icon} />
              </div>
              <h3 className="font-headline-md text-headline-md text-on-surface">
                {n.label}
              </h3>
              <p className="font-body-sm text-on-surface-variant">{n.desc}</p>
              <span className="mt-1 inline-flex items-center gap-1 font-label-bold text-industrial-green">
                Shop now
                <Icon name="arrow_forward" className="text-sm transition-transform group-hover:translate-x-1" />
              </span>
            </button>
          ))}
        </div>
      </div>
    </section>
  );
}

function ViscosityBento() {
  return (
    <section className="bg-surface-subtle px-margin-mobile py-section-gap md:px-margin-desktop">
      <div className="grid grid-cols-1 gap-gutter md:grid-cols-12">
        <div className="rounded-xl border border-outline-variant bg-safety-white p-spacing-component-gap shadow-sm md:col-span-8">
          <h2 className="mb-6 font-headline-lg text-headline-lg">
            Dynamic Viscosity Index
          </h2>
          <p className="mb-8 text-on-surface-variant">
            Understanding the SAE J300 standard is critical for ensuring
            component longevity. Our lubricants are formulated to maintain shear
            stability under extreme thermal loads.
          </p>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            {VISCOSITY_GRADES.map((item) => (
              <div
                key={item.grade}
                className="rounded-lg border border-outline-variant bg-surface-container-low p-6"
              >
                <h3 className="mb-2 font-headline-md text-headline-md text-industrial-green">
                  {item.grade}
                </h3>
                <p className="mb-4 text-body-sm">{item.desc}</p>
                <div className="flex items-center gap-2 text-primary">
                  <Icon name={item.icon} />
                  <span className="font-label-bold">{item.badge}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="flex flex-col justify-between rounded-xl bg-carbon-gray p-spacing-component-gap text-left text-safety-white md:col-span-4">
          <div>
            <h2 className="mb-4 text-left font-headline-md text-headline-md">
              Global Standards
            </h2>
            <div className="space-y-4">
              {GLOBAL_STANDARDS.map((item) => (
                <div
                  key={item.code}
                  className="flex gap-3 rounded-lg border border-white/10 bg-white/5 p-4"
                >
                  <Icon name="verified" className="mt-0.5 text-industrial-green" />
                  <div>
                    <div className="mb-1 font-label-bold text-safety-white">
                      {item.code}
                    </div>
                    <p className="font-body-sm text-surface-variant">
                      {item.desc}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="mt-8 border-t border-white/10 pt-8">
            <img
              src={IMAGES.carOilPour}
              alt="Synthetic motor oil pour"
              className="mb-4 h-32 w-full rounded object-cover"
            />
            <p className="text-body-sm italic">"Precision at the molecular level."</p>
          </div>
        </div>
      </div>
    </section>
  );
}

function OemApprovals() {
  return (
    <section className="px-margin-mobile py-section-gap md:px-margin-desktop">
      <div className="mb-12">
        <h2 className="mb-4 font-headline-lg text-headline-lg">
          Manufacturer Specifications
        </h2>
        <p className="max-w-2xl text-on-surface-variant">
          Velocity Industrial lubricants are rigorously tested to meet and exceed
          the stringent requirements of the world's leading automotive
          manufacturers.
        </p>
      </div>
      <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
        {OEM_APPROVALS.map((item) => (
          <div
            key={item.maker}
            className="flex flex-col items-center border border-outline-variant p-8 text-center transition-all hover:shadow-md"
          >
            <Icon name={item.icon} className="mb-4 text-4xl text-primary" />
            <h4 className="mb-2 font-label-bold">{item.maker}</h4>
            <p className="text-table-data">{item.spec}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

function LabTable() {
  return (
    <section className="bg-surface-container px-margin-mobile py-section-gap md:px-margin-desktop">
      <div className="overflow-hidden rounded-xl border border-outline-variant bg-safety-white shadow-sm">
        <div className="bg-carbon-gray p-6 text-safety-white">
          <h3 className="font-headline-md text-headline-md">
            Laboratory Analysis & Performance Metrics
          </h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full zebra-table">
            <thead className="border-b border-outline bg-surface-dim">
              <tr>
                <th className="p-4 text-left font-label-bold text-on-surface">
                  Test Parameter
                </th>
                <th className="p-4 text-left font-label-bold text-on-surface">
                  Method
                </th>
                <th className="p-4 text-left font-label-bold text-on-surface">
                  Velocity Elite 5W-30
                </th>
                <th className="p-4 text-left font-label-bold text-on-surface">
                  Velocity Max 10W-40
                </th>
              </tr>
            </thead>
            <tbody className="text-table-data">
              {LAB_ROWS.map((row, i) => (
                <tr
                  key={row.param}
                  className={`border-b border-outline-variant ${
                    i % 2 === 1 ? "bg-surface-subtle" : ""
                  }`}
                >
                  <td className="p-4 font-label-bold">{row.param}</td>
                  <td className="p-4">{row.method}</td>
                  <td className="p-4">{row.elite}</td>
                  <td className="p-4">{row.max}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

function WearProtection() {
  return (
    <section className="grid items-center gap-16 px-margin-mobile py-section-gap md:grid-cols-2 md:px-margin-desktop">
      <div className="relative">
        <img
          src={IMAGES.carEngineInternals}
          alt="Engine internals with protective lubricant film"
          className="aspect-square w-full rounded-xl object-cover shadow-lg"
        />
        <div className="absolute -bottom-6 -right-6 max-w-xs rounded-lg bg-industrial-green p-8 text-safety-white">
          <div className="mb-2 text-4xl font-bold">99.8%</div>
          <p className="font-label-bold">
            Reduction in critical engine wear compared to industry standards.
          </p>
        </div>
      </div>
      <div>
        <h2 className="mb-6 font-headline-lg text-headline-lg">
          Advanced Friction Management
        </h2>
        <p className="mb-8 text-body-lg">
          Modern engines operate under higher pressures than ever before. Our
          proprietary anti-wear additive package creates a molecular-level shield
          on critical engine surfaces.
        </p>
        <div className="space-y-6">
          {FRICTION_BENEFITS.map((item) => (
            <div key={item.title} className="flex gap-4">
              <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-primary-container">
                <Icon name={item.icon} className="text-on-primary-container" />
              </div>
              <div>
                <h4 className="font-label-bold">{item.title}</h4>
                <p className="text-body-sm text-on-surface-variant">{item.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CtaSection() {
  return (
    <section className="mb-section-gap mx-margin-desktop rounded-2xl bg-industrial-green px-margin-mobile py-section-gap text-center text-safety-white md:px-margin-desktop">
      <h2 className="mb-4 font-display-lg text-display-lg">
        Ready to optimize your fleet?
      </h2>
      <p className="mb-8 max-w-2xl mx-auto opacity-90 text-body-lg">
        Consult with our technical engineers to find the precise lubricant
        specification for your specific automotive application.
      </p>
      <div className="flex flex-col justify-center gap-4 sm:flex-row">
        <button className="rounded-lg bg-safety-white px-10 py-4 font-label-bold text-label-bold text-industrial-green transition-all hover:bg-surface-container">
          Request Technical Quote
        </button>
        <button className="rounded-lg border border-safety-white px-10 py-4 font-label-bold text-label-bold text-safety-white transition-all hover:bg-white/10">
          Find a Distributor
        </button>
      </div>
    </section>
  );
}

export default function CarMotor() {
  return (
    <main>
      <Hero />
      <ShopByNeed />
      <div className="mx-auto max-w-container-max">
        <ViscosityBento />
        <OemApprovals />
        <LabTable />
        <WearProtection />
        <CtaSection />
      </div>
    </main>
  );
}
